"""
Demo: Premium React Component via Open Grace Swarm.
This script demonstrates the end-to-end autonomous flow:
Planning -> Research -> Coding -> Evaluation -> Memory Distillation.
"""

import asyncio
import os
import json
from open_grace.agents.agent_swarm import AgentSwarm
from open_grace.memory.long_term_memory import get_ltm

async def run_demo():
    print("\n🚀 Starting Open Grace AI OS Practical Demonstration")
    print("--------------------------------------------------")
    
    swarm = AgentSwarm()
    await swarm.initialize()
    
    # Define a high-level task for the swarm
    task_description = """
    Create a premium React component for a Profile Card named 'GlassCard.tsx'.
    
    Design Requirements:
    - Use Glassmorphism effects (backdrop-filter: blur, semi-transparent backgrounds).
    - Use a vibrant but harmonious color palette (e.g., deep purples and blues with subtle gold accents).
    - Include hover micro-animations for interactivity.
    - Ensure it is responsive and uses semantic HTML.
    - Export it as a functional React component using TypeScript.
    
    Location: workspace/mini_react_demo/GlassCard.tsx
    """
    
    print(f"\n📝 Task: {task_description.split('.')[0].strip()}...")
    print("\n⏳ Step 1: Swarm Planning & Execution...")
    
    # We use execute which handles the following internally:
    # 1. Planner creates a strategy.
    # 2. Agents execute steps (Coder writes code, Researcher finds patterns).
    # 3. Evaluator critiques the result.
    # 4. LTM distills and stores the knowledge.
    
    result = await swarm.execute(task_description)
    
    print("\n✅ Task Execution Complete!")
    
    # Show the Planning output
    if "plan" in result:
        print("\n📋 Swarm Execution Plan:")
        plan = result["plan"]
        for step in plan.get("steps", []):
            print(f"   - [{step.get('agent_type')}] {step.get('description')}")
            
    # Show the final code snippet (if generated by Coder)
    # The coder writes it to the file, but we can read it back for show
    file_path = "workspace/mini_react_demo/GlassCard.tsx"
    abs_path = os.path.join(os.getcwd(), file_path)
    if os.path.exists(abs_path):
        print(f"\n📂 Final Component written to: {file_path}")
        with open(abs_path, "r") as f:
            lines = f.readlines()
            print("\n💻 Code Preview (First 20 lines):")
            print("".join(lines[:20]))
            print("   ...")
    
    # Show the Evaluation
    if "evaluation" in result:
        eval_report = result["evaluation"]
        print("\n⭐ Swarm Self-Evaluation:")
        print(f"   Quality Score: {eval_report['quality_score']}/10")
        print(f"   Alignment: {eval_report['alignment_score']}/10")
        print(f"   Critique: {eval_report['critique']}")
        print(f"   Improvement Strategy: {eval_report['improvement_strategies'][0] if eval_report['improvement_strategies'] else 'N/A'}")

    print("\n🧠 Step 2: Verifying Memory Distillation...")
    ltm = get_ltm()
    # Check if the memory now contains lessons about Glassmorphism
    context = ltm.recall_context("Glassmorphism design patterns")
    
    print("\n🔍 Recalled Lessons from Long-Term Memory:")
    if context:
        print(context)
    else:
        print("   (LTM is currently processing the new insights...)")

    print("\n--- Demonstration Complete ---")

if __name__ == "__main__":
    asyncio.run(run_demo())
